### ISSUE TITLE
Question about llama_flash_attn_monkey_patch 

### ISSUE THREAD

**Issue by mmmwhy** [PKU-YuanGroup/Chat-UniVi#35]
https://github.com/PKU-YuanGroup/Chat-UniVi/blob/main/ChatUniVi/train/llama_flash_attn_monkey_patch.py  is different with https://github.com/haotian-liu/LLaVA/blob/main/llava/train/llama_flash_attn_monkey_patch.py

for example:

https://github.com/PKU-YuanGroup/Chat-UniVi/blob/main/ChatUniVi/train/llama_flash_attn_monkey_patch.py
![image](https://github.com/PKU-YuanGroup/Chat-UniVi/assets/11297491/8734a20b-9fca-40eb-ac42-9bcfe4ae5ae0)
and 

https://github.com/haotian-liu/LLaVA/blob/main/llava/train/llama_flash_attn_monkey_patch.py
![image](https://github.com/PKU-YuanGroup/Chat-UniVi/assets/11297491/a6e1dcb8-215a-45c1-ab86-98d0381e4058)

it seems chat-univi change some code in **llama_flash_attn_monkey_patch**, can you help explain the reason for modifying the code? ♥️

**Comment by jpthu17** [comment]
We use standard multi-head attention. Since LLaMA 3 uses grouped-query attention, we guess that LLaVA made changes following LLaMA 3. (The main purpose of grouped-query attention is to reduce KV cache.)
![image](https://github.com/PKU-YuanGroup/Chat-UniVi/assets/53246557/c6e95560-6553-4b05-8eed-8f9cbbb19e12)
